pip install fiftyone
pip install fiftyone_brain
pip install fiftyone_db
pip install imgui
pip install matplotlib
pip install numpy
pip install pandas
pip install Pillow
pip install pygame
pip install pygame_gui
pip install pyglm
pip install pymeshlab
pip install PyOpenGL
pip install PyOpenGL
pip install scikit-image
pip install ultralytics
